apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: l5widl2ul-go 
  janus-idp.io/tekton: l5widl2ul-go
  backstage.io/kubernetes-id: l5widl2ul-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: l5widl2ul-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml