apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: l5widl2ul-go-gitops
  description: This is GitOps manifest for l5widl2ul-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=l5widl2ul-go
    backstage.io/kubernetes-id: l5widl2ul-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: l5widl2ul-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:l5widl2ul-go
